### ISSUE TITLE
Crash when using mystcraft and weCui

### ISSUE THREAD

**Issue by jasonmbrown** [hexosse/WorldEditCUI-Forge-Edition#3]
The full crash log http://pastebin.com/qCcBnMx5 (Clients side)

The Server reports an invalid/unhandled packet, gives worthless errors related to common java libraries.

Basically I created a world with mystcraft, Entered it. And proceeded To crash every time I rejoined the server. Im not sure whats happening althought I havent tried entering any other dimensions either so It might not be Directly Tied to mystcraft.

`java.lang.NullPointerException: Unexpected error
    at com.github.hexosse.wecuife.d.a.b(CUIPacket.java:109)
    at com.github.hexosse.wecuife.j.b.a(CUIListenerPlayerJoin.java:73)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1509_b_a_TickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

Theres the Stacktrace for the crash. Let me know if u need anything else

PS:Im on version 1.7.10 latest forge for 1.7.10

**Comment by hexosse** [comment]
Hi,
Version 1.0.3 should solve your problem.
Let me know if it works

**Comment by hexosse** [comment]
I suppose that version 1.0.3 solved your problem.
