### ISSUE TITLE
Please update modid to be lowercase to support 1.11

### ISSUE THREAD

**Issue by bendoerr** [hexosse/WorldEditCUI-Forge-Edition#5]
FML won't load the mod since the modid needs to be lowercase in MC 1.11.

Here is the error:

```
15:07:30] [Client thread/WARN] [FML]: ****************************************
[15:07:30] [Client thread/WARN] [FML]: * The modid WorldEditCuiFe is not the same as it's lowercase version. Lowercasing is enforced in 1.11
[15:07:30] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:143)
[15:07:30] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:126)
[15:07:30] [Client thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:07:30] [Client thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:07:30] [Client thread/WARN] [FML]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:07:30] [Client thread/WARN] [FML]: *  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)...
[15:07:30] [Client thread/WARN] [FML]: ****************************************
[15:07:30] [Client thread/ERROR] [FML]: Unable to construct net.minecraftforge.fml.common.Mod container
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
	at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:86) [ModContainerFactory.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:87) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:49) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:78) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:141) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:382) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:522) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:438) [beq.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350) [beq.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: The modid WorldEditCuiFe is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
	at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:144) ~[FMLModContainer.class:?]
	at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:126) ~[FMLModContainer.class:?]
	... 21 more
```

I'd drop you a PR but it doesn't look like you've pushed the relevant code. On top of that you obfuscated for some odd reason. EPL is copyleft if I recall but folk are already addressing that in #2.

Anyway, I manually edited the bytecode and lowercased what looked like modid throughout. I've confirmed that everything works as expected after doing that.

**Comment by hexosse** [comment]
I just push a new release on curseforge v1.0.5.
I've updated the modid to be lowercase to support 1.11

**Comment by bendoerr** [comment]
Thank you
